FROM amd64/python:3.7-slim-buster

WORKDIR /app

ENV PYTHONPATH /app/.

COPY ./images ./

RUN apt-get update && apt-get install -y libglib2.0-0 libgl1-mesa-glx && rm -rf /var/lib/apt/lists/*
RUN apt-get install unixodbc
RUN pip install opencv-python numpy scipy pyodbc

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]